# Generated by Django 3.2.7 on 2021-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
