# Generated by Django 3.2.7 on 2021-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_patient_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
