# Generated by Django 3.2.7 on 2021-09-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_patient_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
