# Generated by Django 3.2.7 on 2021-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_patient_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='anamnesi_personale',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
