# Generated by Django 3.2.7 on 2021-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_patient_anamnesi_personale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='anamnesi_personale',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
