# Generated by Django 3.2.7 on 2021-10-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_patient_anamnesi_personale'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_patologia', models.CharField(max_length=255)),
                ('patologia', models.CharField(max_length=255)),
                ('codice_sintomo', models.CharField(max_length=255)),
                ('sintomo', models.CharField(max_length=255)),
                ('sintomo_principale', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='anamnesi_personale',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
